export interface TDSCityData {
  province: string;
  city: string;
  tds: number;
}

export const TDS_DATA: TDSCityData[] = [
  { province: '北京', city: '北京', tds: 280 },
  { province: '北京', city: '延庆', tds: 320 },
  { province: '北京', city: '密云', tds: 260 },
  { province: '天津', city: '天津', tds: 350 },
  { province: '天津', city: '塘沽', tds: 420 },
  { province: '上海', city: '上海', tds: 180 },
  { province: '上海', city: '浦东', tds: 200 },
  { province: '上海', city: '青浦', tds: 220 },
  { province: '重庆', city: '重庆', tds: 150 },
  { province: '重庆', city: '万州', tds: 180 },
  { province: '重庆', city: '涪陵', tds: 160 },
  { province: '广东', city: '广州', tds: 120 },
  { province: '广东', city: '深圳', tds: 90 },
  { province: '广东', city: '珠海', tds: 85 },
  { province: '广东', city: '东莞', tds: 110 },
  { province: '广东', city: '佛山', tds: 130 },
  { province: '广东', city: '中山', tds: 100 },
  { province: '广东', city: '汕头', tds: 140 },
  { province: '广东', city: '湛江', tds: 160 },
  { province: '江苏', city: '南京', tds: 240 },
  { province: '江苏', city: '苏州', tds: 220 },
  { province: '江苏', city: '无锡', tds: 230 },
  { province: '江苏', city: '常州', tds: 250 },
  { province: '江苏', city: '南通', tds: 260 },
  { province: '江苏', city: '扬州', tds: 210 },
  { province: '江苏', city: '徐州', tds: 300 },
  { province: '江苏', city: '连云港', tds: 320 },
  { province: '浙江', city: '杭州', tds: 110 },
  { province: '浙江', city: '宁波', tds: 130 },
  { province: '浙江', city: '温州', tds: 95 },
  { province: '浙江', city: '绍兴', tds: 120 },
  { province: '浙江', city: '嘉兴', tds: 180 },
  { province: '浙江', city: '金华', tds: 100 },
  { province: '浙江', city: '台州', tds: 90 },
  { province: '山东', city: '济南', tds: 360 },
  { province: '山东', city: '青岛', tds: 280 },
  { province: '山东', city: '烟台', tds: 260 },
  { province: '山东', city: '威海', tds: 220 },
  { province: '山东', city: '潍坊', tds: 340 },
  { province: '山东', city: '淄博', tds: 380 },
  { province: '山东', city: '济宁', tds: 320 },
  { province: '山东', city: '临沂', tds: 300 },
  { province: '河南', city: '郑州', tds: 420 },
  { province: '河南', city: '洛阳', tds: 380 },
  { province: '河南', city: '开封', tds: 400 },
  { province: '河南', city: '新乡', tds: 450 },
  { province: '河南', city: '南阳', tds: 350 },
  { province: '河南', city: '商丘', tds: 480 },
  { province: '河北', city: '石家庄', tds: 450 },
  { province: '河北', city: '唐山', tds: 420 },
  { province: '河北', city: '保定', tds: 400 },
  { province: '河北', city: '秦皇岛', tds: 380 },
  { province: '河北', city: '邯郸', tds: 460 },
  { province: '河北', city: '廊坊', tds: 430 },
  { province: '四川', city: '成都', tds: 140 },
  { province: '四川', city: '绵阳', tds: 160 },
  { province: '四川', city: '德阳', tds: 180 },
  { province: '四川', city: '宜宾', tds: 120 },
  { province: '四川', city: '乐山', tds: 130 },
  { province: '四川', city: '泸州', tds: 150 },
  { province: '湖北', city: '武汉', tds: 200 },
  { province: '湖北', city: '宜昌', tds: 180 },
  { province: '湖北', city: '襄阳', tds: 220 },
  { province: '湖北', city: '荆州', tds: 240 },
  { province: '湖北', city: '黄石', tds: 210 },
  { province: '湖南', city: '长沙', tds: 110 },
  { province: '湖南', city: '株洲', tds: 130 },
  { province: '湖南', city: '湘潭', tds: 120 },
  { province: '湖南', city: '岳阳', tds: 150 },
  { province: '湖南', city: '衡阳', tds: 140 },
  { province: '福建', city: '福州', tds: 80 },
  { province: '福建', city: '厦门', tds: 70 },
  { province: '福建', city: '泉州', tds: 90 },
  { province: '福建', city: '漳州', tds: 85 },
  { province: '安徽', city: '合肥', tds: 200 },
  { province: '安徽', city: '芜湖', tds: 180 },
  { province: '安徽', city: '蚌埠', tds: 260 },
  { province: '安徽', city: '安庆', tds: 170 },
  { province: '安徽', city: '马鞍山', tds: 220 },
  { province: '江西', city: '南昌', tds: 100 },
  { province: '江西', city: '九江', tds: 120 },
  { province: '江西', city: '赣州', tds: 90 },
  { province: '江西', city: '上饶', tds: 110 },
  { province: '辽宁', city: '沈阳', tds: 320 },
  { province: '辽宁', city: '大连', tds: 260 },
  { province: '辽宁', city: '鞍山', tds: 340 },
  { province: '辽宁', city: '抚顺', tds: 300 },
  { province: '吉林', city: '长春', tds: 280 },
  { province: '吉林', city: '吉林', tds: 260 },
  { province: '吉林', city: '四平', tds: 300 },
  { province: '黑龙江', city: '哈尔滨', tds: 240 },
  { province: '黑龙江', city: '齐齐哈尔', tds: 280 },
  { province: '黑龙江', city: '大庆', tds: 260 },
  { province: '黑龙江', city: '牡丹江', tds: 200 },
  { province: '山西', city: '太原', tds: 480 },
  { province: '山西', city: '大同', tds: 520 },
  { province: '山西', city: '运城', tds: 450 },
  { province: '山西', city: '临汾', tds: 400 },
  { province: '陕西', city: '西安', tds: 420 },
  { province: '陕西', city: '咸阳', tds: 450 },
  { province: '陕西', city: '宝鸡', tds: 380 },
  { province: '陕西', city: '榆林', tds: 500 },
  { province: '甘肃', city: '兰州', tds: 480 },
  { province: '甘肃', city: '天水', tds: 360 },
  { province: '甘肃', city: '酒泉', tds: 550 },
  { province: '青海', city: '西宁', tds: 420 },
  { province: '青海', city: '格尔木', tds: 580 },
  { province: '宁夏', city: '银川', tds: 460 },
  { province: '宁夏', city: '石嘴山', tds: 500 },
  { province: '内蒙古', city: '呼和浩特', tds: 400 },
  { province: '内蒙古', city: '包头', tds: 450 },
  { province: '内蒙古', city: '鄂尔多斯', tds: 480 },
  { province: '内蒙古', city: '赤峰', tds: 380 },
  { province: '新疆', city: '乌鲁木齐', tds: 520 },
  { province: '新疆', city: '库尔勒', tds: 480 },
  { province: '新疆', city: '伊犁', tds: 300 },
  { province: '西藏', city: '拉萨', tds: 180 },
  { province: '西藏', city: '日喀则', tds: 200 },
  { province: '云南', city: '昆明', tds: 120 },
  { province: '云南', city: '大理', tds: 100 },
  { province: '云南', city: '丽江', tds: 80 },
  { province: '云南', city: '曲靖', tds: 140 },
  { province: '贵州', city: '贵阳', tds: 130 },
  { province: '贵州', city: '遵义', tds: 150 },
  { province: '贵州', city: '六盘水', tds: 180 },
  { province: '广西', city: '南宁', tds: 100 },
  { province: '广西', city: '桂林', tds: 80 },
  { province: '广西', city: '柳州', tds: 120 },
  { province: '广西', city: '北海', tds: 150 },
  { province: '海南', city: '海口', tds: 120 },
  { province: '海南', city: '三亚', tds: 140 },
  { province: '台湾', city: '台北', tds: 80 },
  { province: '台湾', city: '高雄', tds: 90 },
  { province: '香港', city: '香港', tds: 70 },
  { province: '澳门', city: '澳门', tds: 65 },
];

export const TDS_LEVELS = [
  { min: 0, max: 50, label: '纯净水', color: 'text-emerald-600', bg: 'bg-emerald-50', border: 'border-emerald-200', desc: 'TDS值极低，水质非常纯净，几乎不含溶解性固体' },
  { min: 50, max: 100, label: '优质', color: 'text-green-600', bg: 'bg-green-50', border: 'border-green-200', desc: 'TDS值较低，水质优良，可直接饮用或简单过滤后饮用' },
  { min: 100, max: 200, label: '良好', color: 'text-lime-600', bg: 'bg-lime-50', border: 'border-lime-200', desc: 'TDS值适中，水质一般良好，建议过滤后饮用口感更佳' },
  { min: 200, max: 300, label: '一般', color: 'text-amber-600', bg: 'bg-amber-50', border: 'border-amber-200', desc: 'TDS值偏高，水中矿物质含量较高，建议安装净水器' },
  { min: 300, max: 500, label: '较差', color: 'text-orange-600', bg: 'bg-orange-50', border: 'border-orange-200', desc: 'TDS值较高，水垢明显，强烈建议安装净水器改善水质' },
  { min: 500, max: 10000, label: '很差', color: 'text-red-600', bg: 'bg-red-50', border: 'border-red-200', desc: 'TDS值很高，水质较差，必须安装RO反渗透净水器才能饮用' },
];

export function getTDSLevel(tds: number): typeof TDS_LEVELS[number] {
  for (const level of TDS_LEVELS) {
    if (tds >= level.min && tds < level.max) return level;
  }
  return TDS_LEVELS[TDS_LEVELS.length - 1];
}

export function getProvinces(): string[] {
  const set = new Set(TDS_DATA.map((d: TDSCityData) => d.province));
  return Array.from(set).sort();
}

export function getCitiesByProvince(province: string): TDSCityData[] {
  return TDS_DATA.filter((d: TDSCityData) => d.province === province);
}
